### ISSUE TITLE
本家のREADME.txtが同梱されている

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox_nemo_core#2]
## 不具合の内容

タイトル通りです。

### 現象・ログ

本家のREADME.txtが同梱されています。（voicevox_get_metas_jsonでNemoのCoreであることは確認済です）
```
❯ head -50 README.txt
これは VOICEVOX コアライブラリです。
https://github.com/Hiroshiba/voicevox_core

## 許諾内容

1. 商用・非商用問わず利用することができます
2. アプリケーションに組み込んで再配布することができます
3. 作成された音声を利用する際は、各音声ライブラリの規約に従ってください
4. 作成された音声の利用を他者に許諾する際は、当該他者に対し本許諾内容の 3 及び 4 の遵守を義務付けてください

## 音声ライブラリの利用規約

### 四国めたん

四国めたんの音声ライブラリを用いて生成した音声は、
「VOICEVOX:四国めたん」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://zunko.jp/con_ongen_kiyaku.html
...
```

### 再現手順

1. https://github.com/VOICEVOX/voicevox_nemo_core/releases/tag/0.14.0 をダウンロードする
2. README.txtを開く

nemo確認スクリプトです。
```py
import ctypes
import json

vv = ctypes.CDLL("./libvoicevox_core.so") # ここのDLL名は良い感じに置き換えて下さい

vv.voicevox_get_metas_json.restype = ctypes.c_char_p

metas = json.loads(vv.voicevox_get_metas_json().decode("utf-8"))

for meta in metas:
    print("-", meta["name"])
```
```
❯ py test.py
- 女声1
- 女声2
- 女声3
- 女声4
- 女声5
- 女声6
- 男声1
- 男声2
- 男声3
```

### 期待動作

Voicevox Nemo Coreに沿ったREADME.txtが配布されている

## VOICEVOXのバージョン

0.14.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

## その他

`Hiroshiba/voicevox_core`は本家も直してもいいかも

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！！

一旦`0.14.0`の全てのZIPファイル内のREADMEをNemo用のに置き換えて再アップロードしたいと思います。
2023/11/17 11:08　しました！

> Hiroshiba/voicevox_coreは本家も直してもいいかも

確認したところ本家の方は修正されてそうでした！

**Comment by Hiroshiba** [comment]
解決なのでclose！
